services:
  postgres:
    image: postgres:16
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ordini_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: ecommerce-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - kafka_data:/var/lib/kafka/data

  utenti-webapi:
    build:
      context: .
      dockerfile: src/Services/Utenti/Utenti.WebApi/Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: ecommerce-utenti-webapi
    ports:
      - "5142:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__UtentiDb: "Host=postgres;Port=5432;Database=utenti_db;Username=postgres;Password=postgres"
      JwtSettings__Secret: "una-chiave-segreta-lunga-almeno-32-caratteri-cambiala"
      JwtSettings__Issuer: "Ecommerce.Utenti"
      JwtSettings__Audience: "Ecommerce"
      JwtSettings__ExpirationMinutes: "60"
      Kafka__Enable: "true"
      Kafka__AdminClient__BootstrapServers: "kafka:9092"
      Kafka__ProducerClient__BootstrapServers: "kafka:9092"
      Kafka__ProducerService__DelaySeconds: "10"
      Kafka__ProducerService__IntervalSeconds: "60"
      Kafka__Topics__UtenteRegistrato: "UtenteRegistrato"
    depends_on:
      - postgres
      - kafka

volumes:
  postgres_data:
  kafka_data: